# Dependencies
markdown:         redcarpet
highlighter:	  pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Sid Ngeth'
tagline:          'A blog about anything'
description:      ''
url:              http://sidngeth.com/
baseurl: ""

author:
  name:           'Sid Ngeth'
  url:            http://sidngeth.com/

paginate:         5

github:
  repo:           https://github.com/sngeth