# Dependencies
gems: [jekyll-paginate]
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Sid Ngeth's Blog"
tagline:          'A blog about anything (but mostly development)'
description:      ''
url:              http://sidngeth.com/
baseurl: ""

author:
  name:           'Sid Ngeth'
  url:            http://sidngeth.com/

paginate:         5

github:
  repo:           https://github.com/sngeth

plugins:
  - jekyll-paginate
