#!/bin/bash
# Automated Voxtral TTS runner for The Sid Dispatch
# Runs on your Mac after the dispatch HTML is generated and pushed.
# Schedule: launchd at 7:30am daily (30min buffer after dispatch generation)

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
LOG_FILE="$REPO_DIR/logs/dispatch-audio.log"
DATE=$(date +%Y-%m-%d)

mkdir -p "$REPO_DIR/logs"

exec >> "$LOG_FILE" 2>&1
echo ""
echo "========================================"
echo "Dispatch Audio Run: $DATE $(date +%H:%M:%S)"
echo "========================================"

cd "$REPO_DIR"

# Stash any local changes so pull --rebase can proceed
STASHED=false
if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "→ Stashing unstaged/staged changes..."
  git stash push --include-untracked -m "auto-stash before dispatch pull"
  STASHED=true
fi

# Pull latest dispatch HTML (generated by container at 7am)
echo "→ Pulling latest dispatch..."
git pull --rebase origin master

if [ "$STASHED" = true ]; then
  echo "→ Restoring stashed changes..."
  git stash pop
fi

# Check if today's dispatch exists
if [ ! -f "dispatch/index.html" ]; then
  echo "✗ dispatch/index.html not found. Skipping."
  exit 1
fi

# Check if audio already generated for today (release already exists)
TAG="dispatch-audio-$DATE"
if gh release view "$TAG" --repo sngeth/sngeth.github.io > /dev/null 2>&1; then
  echo "→ Release $TAG already exists. Skipping."
  exit 0
fi

# Run Voxtral TTS
echo "→ Generating audio for $DATE..."
uv run scripts/generate_dispatch_audio.py --date "$DATE"

# Commit patched HTML (audio player injected, Web Speech API stripped)
echo "→ Committing patched HTML..."
git add dispatch/
if git status --porcelain dispatch/ | grep -q '^'; then
  git commit -m "🎧 Audio: $DATE"
  git push origin HEAD
  echo "✓ Pushed patched HTML"
else
  echo "→ No HTML changes to commit"
fi

echo "✓ Done: $DATE"
