#!/bin/bash
# Automated ElevenLabs TTS runner for The Sid Dispatch
# Runs on your Mac after the dispatch HTML is generated and pushed.
# Schedule: launchd at 7:30am daily (30min buffer after dispatch generation)

set -euo pipefail

PATCH_ONLY=false
FORCE=false
for arg in "$@"; do
  case "$arg" in
    --patch-only) PATCH_ONLY=true ;;
    --force) FORCE=true ;;
  esac
done

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
LOG_FILE="$REPO_DIR/logs/dispatch-audio.log"
DATE=$(TZ=America/Los_Angeles date +%Y-%m-%d)

mkdir -p "$REPO_DIR/logs"

exec >> "$LOG_FILE" 2>&1
echo ""
echo "========================================"
echo "Dispatch Audio Run: $DATE $(date +%H:%M:%S)"
echo "========================================"

cd "$REPO_DIR"

# Stash any local changes so pull --rebase can proceed
STASHED=false
if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "→ Stashing unstaged/staged changes..."
  git stash push --include-untracked -m "auto-stash before dispatch pull"
  STASHED=true
fi

# Pull latest dispatch HTML (generated by container at 7am)
echo "→ Pulling latest dispatch..."
git pull --rebase origin master

if [ "$STASHED" = true ]; then
  echo "→ Restoring stashed changes..."
  git stash pop
fi

# Check if today's dispatch exists
if [ ! -f "dispatch/index.html" ]; then
  echo "✗ dispatch/index.html not found. Skipping."
  exit 1
fi

# Check if audio already generated for today (check R2 for full-edition.mp3)
R2_URL="https://pub-9763ba4e3f6c471f86b2b40bc004a479.r2.dev/$DATE/full-edition.mp3"
if [ "$PATCH_ONLY" = true ]; then
  if ! curl -sf --head "$R2_URL" > /dev/null 2>&1; then
    echo "✗ Audio not found on R2 for $DATE. Cannot --patch-only."
    exit 1
  fi
  echo "→ Re-patching HTML for $DATE from existing R2 audio..."
  uv run scripts/generate_dispatch_audio.py --date "$DATE" --patch-only
else
  if curl -sf --head "$R2_URL" > /dev/null 2>&1; then
    if [ "$FORCE" = true ]; then
      echo "→ Audio exists on R2. --force: regenerating..."
    else
      echo "→ Audio already exists on R2 for $DATE. Skipping."
      exit 0
    fi
  fi
  echo "→ Generating audio for $DATE..."
  uv run scripts/generate_dispatch_audio.py --date "$DATE"
fi

# Commit patched HTML (audio player injected, Web Speech API stripped)
echo "→ Committing patched HTML..."
git add dispatch/
if git status --porcelain dispatch/ | grep -q '^'; then
  if [ "$PATCH_ONLY" = true ]; then
    git commit -m "🎧 Audio re-patch: $DATE"
  else
    git commit -m "🎧 Audio: $DATE"
  fi
  git push origin HEAD
  echo "✓ Pushed patched HTML"
else
  echo "→ No HTML changes to commit"
fi

echo "✓ Done: $DATE"
